server:
  port: 8086
  tomcat:
    threads:
      min-spare: 10
      max: 200
    max-connections: 8192
    accept-count: 100
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: beckroot
    password: Beckroot147
    url: jdbc:mysql://localhost:3306/java_spring_boot_db?useUnicode=true&useSSL=false&characterEncoding=utf8